language: python
python: 
  - '3.8'

script:
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
deploy:
  - provider: pages:git
  - verbose: true
  - token: $GITHUB_TOKEN
  - edge: true
  - local_dir: ./docs/build/html/
  - keep_history: true